#!/usr/bin/env bash
#accepts two arguments, displays information for the specified subdomain

get_domain_info () {
    line=$(dig $2.$1 | grep -A1 'ANSWER SECTION:' | tr '\t' '\n' | tail -2 | tr '\n' ' ')
    echo "$2 $line" | awk '{print "The subdomain " $1 " is a " $2 " record and points to " $3}'
}

SUBDOMAINS=("www"  "lb-01" "web-01" "web-02")

if [ "$#" == 1 ];
then
  for sub in ${SUBDOMAINS[@]}; do
    get_domain_info "$1" $sub
  done
elif [ "$#" == 2 ]
then
  get_domain_info "$1" "$2"
fi
