#!/usr/bin/env bash
# Installs Nginx
# Configure Nginx so that its HTTP response contains a custom header

apt-get update
apt-get install nginx

echo "server {
        listen 80 default_server;
        listen [::]:80 default_server;
        root /var/www/html;
        index index.html index.htm index.nginx-debian.html;
        server_name _;
        location / {
                add_header X-Served-By $HOSTNAME;
                try_files $uri $uri/ =404;
        }
}
" > /etc/nginx/sites-available/default

service nginx restart
