#!/usr/bin/env bash
# Install and configure HAproxy on your lb-01 server.

apt-get install --no-install-recommends software-properties-common
add-apt-repository ppa:vbernat/haproxy-2.6
apt-get install haproxy=2.6.\*

echo "ENABLED=1" >> /etc/default/haproxy

echo "
defaults
    retries 3
    timeout connect  5000
    timeout client  10000
    timeout server  10000

listen load_balancer
    bind *:80
    mode http
    option httpclose
    option forwardfor

    balance roundrobin
    server 143473-web-01 54.237.35.82:80 check
    server 143473-web-02 18.209.224.87:80 check
" >> /etc/haproxy/haproxy.cfg

sudo service haproxy start
