#!/usr/bin/env bash
# Bash script that displays "To infinity and beyond indefinitely"
# and "I am invincible!!!" with a sleep 2 between each loop

trap "echo I am invincible!!!" SIGTERM
while true
do
        echo To infinity and beyond
        sleep 2
done  
