#!/usr/bin/env bash
# Changes IP address from localhost to 127.0.0.2 and facebook to 8.8.8.8 using hosts file
cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
echo '8.8.8.8	facebook.com' >> ~/hosts.new
cat ~/hosts.new > /etc/hosts
