#!/usr/bin/env bash
# Changes IP address from localhost to 127.0.0.2 and facebook to 8.8.8.8 using hosts file
cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts
