#!/usr/bin/env bash
# running as nginx user and listens on port 8080
pkill -f apache2
chown nginx /etc/nginx/nginx.conf
chmod 740 /etc/nginx/nginx.conf
sed -i "s/80 default_server/8080 default_server/" /etc/nginx/sites-available/default
sudo -u nginx service nginx start
